name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        environment:
          - POSTGRESQL_USERNAME=postgres
          - POSTGRESQL_PASSWORD=postgres
          - POSTGRESQL_DATABASE=apisolid

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: '21.3.0'
          cache: 'pnpm'

      - run: pnpm install 
      
      - run: pnpm test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/apisolid?schema=public"
        